# 版本号
[versions]
common_base = "1.0.0"
common_reflect = "1.0.0"


# 组件
[libraries]
common_base = { group = "net.bi4vmr.tool.kotlin", name = "common-base", version.ref = "common_base" }
common_reflect = { group = "net.bi4vmr.tool.kotlin", name = "common-reflect", version.ref = "common_reflect" }
