# 版本号
[versions]
common_base = "1.0.0"
common_reflect = "1.0.0"

storage_file = "1.0.0"

serial_basecode = "1.0.0"
serial_gson = "1.0.0"

math_base = "1.0.0"

finance_base = "1.0.0"

security_digest = "1.0.0"


# 组件
[libraries]
common_base = { group = "net.bi4vmr.tool.java", name = "common-base", version.ref = "common_base" }
common_reflect = { group = "net.bi4vmr.tool.java", name = "common-reflect", version.ref = "common_reflect" }

storage_file = { group = "net.bi4vmr.tool.java", name = "storage-file", version.ref = "storage_file" }

serial_basecode = { group = "net.bi4vmr.tool.java", name = "serialization-basecode", version.ref = "serial_basecode" }
serial_gson = { group = "net.bi4vmr.tool.java", name = "serialization-gson", version.ref = "serial_gson" }

math_base = { group = "net.bi4vmr.tool.java", name = "math-base", version.ref = "math_base" }

finance_base = { group = "net.bi4vmr.tool.java", name = "finance-base", version.ref = "finance_base" }

security_digest = { group = "net.bi4vmr.tool.java", name = "security-digest", version.ref = "security_digest" }


# Gradle 插件
[plugins]
# ----- Java -----
# Java 版本配置
java_version = { id = "net.bi4vmr.gradle.plugin.java.version" }
# Maven 公开仓库
repo_public = { id = "net.bi4vmr.gradle.plugin.repo.public" }
# Maven 私有仓库
repo_private = { id = "net.bi4vmr.gradle.plugin.repo.private" }
# Maven Publish 私有仓库配置
publish_private = { id = "net.bi4vmr.gradle.plugin.maven.publish" }
# Maven Publish 私有仓库配置 (KMP)
publish_private_kmp = { id = "net.bi4vmr.gradle.plugin.maven.publish.kmp" }
